//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medosmotr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Посещение
    {
        public int Код_посещения { get; set; }
        public int Код_пациента { get; set; }
        public int Код_специалиста { get; set; }
        public System.DateTime Дата { get; set; }
        public string Заключение { get; set; }
    
        public virtual Пациент Пациент { get; set; }
        public virtual Специалист Специалист { get; set; }
    }
}
