//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medosmotr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Специалист
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Специалист()
        {
            this.Посещение = new HashSet<Посещение>();
        }
    
        public int Код_специалиста { get; set; }
        public string Название { get; set; }
        public string ФИО { get; set; }
        public int Номер_кабинета { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Посещение> Посещение { get; set; }
    }
}
